# see GroupingPathDistanceComposer in pipeline/data/composers/composers.py
pre_context_prompt: "# {}\n"
chunks_sep: "\n\n"
post_context_prompt: "\n\n"
path_comment_template: "# {filename}\n{content}"
ordered_groups: [['.json'], ['.yaml', '.yml'], ['.sh'], ['.md', '.txt', '.rst']]
