train_metrics: [
  # Training Decomposed Cross-entropy
  cross_entropy/attached.yaml,

  # Training Decomposed Exact Match
  exact_match/attached_3.yaml,

  # Training Decomposed Top-k Accuracy
  top_k_accuracy/attached_1.yaml,
  top_k_accuracy/attached_3.yaml,
  top_k_accuracy/attached_5.yaml,
  top_k_accuracy/attached_10.yaml,

  # Training Statistics
  epoch/no_args.yaml,
  lazy_statistic/learning_rate.yaml,
]
valid_metrics: [
  # Validation Decomposed Cross-entropy
  cross_entropy/attached.yaml,

  # Validation Decomposed Exact Match
  exact_match/attached_3.yaml,

  # Validation Decomposed Top-k Accuracy
  top_k_accuracy/attached_1.yaml,
  top_k_accuracy/attached_3.yaml,
  top_k_accuracy/attached_5.yaml,
  top_k_accuracy/attached_10.yaml,

  # Validation Statistics
  epoch/no_args.yaml,
]
