train_metrics: [
  # Training Decomposed Cross-entropy
  cross_entropy/completion.yaml,
  cross_entropy/context.yaml,
  cross_entropy/attached.yaml,
  cross_entropy/detached.yaml,
  cross_entropy/full.yaml,

  # Training Categorized Cross-entropy
  cross_entropy/inproject.yaml,
  cross_entropy/infile.yaml,
  cross_entropy/commited.yaml,
  cross_entropy/common.yaml,
  cross_entropy/non_informative.yaml,
  cross_entropy/random.yaml,

  # Training Decomposed Exact Match
  exact_match/completion_3.yaml,

  # Training Categorized Top-k Accuracy
  top_k_accuracy/inproject_1.yaml,
  top_k_accuracy/inproject_3.yaml,
  top_k_accuracy/inproject_5.yaml,
  top_k_accuracy/inproject_10.yaml,

  # Training Statistics
  epoch/no_args.yaml,
  lazy_statistic/learning_rate.yaml,
]
valid_metrics: [
  # Validation Decomposed Cross-entropy
  cross_entropy/completion.yaml,
  cross_entropy/context.yaml,
  cross_entropy/attached.yaml,
  cross_entropy/detached.yaml,
  cross_entropy/full.yaml,

  # Validation Categorized Cross-entropy
  cross_entropy/inproject.yaml,
  cross_entropy/infile.yaml,
  cross_entropy/commited.yaml,
  cross_entropy/common.yaml,
  cross_entropy/non_informative.yaml,
  cross_entropy/random.yaml,

  # Validation Decomposed Exact Match
  exact_match/completion_3.yaml,

  # Validation Categorized Top-k Accuracy
  top_k_accuracy/inproject_1.yaml,
  top_k_accuracy/inproject_3.yaml,
  top_k_accuracy/inproject_5.yaml,
  top_k_accuracy/inproject_10.yaml,

  # Validation Statistics
  epoch/no_args.yaml,
]
