# TODO: get rid of unnecessary

train_metrics: [
  cross_entropy/attached.yaml,
  cross_entropy/detached.yaml,
  cross_entropy/completion.yaml,
  cross_entropy/context.yaml,
  cross_entropy/full.yaml,
  cross_entropy/commited.yaml,
  cross_entropy/common.yaml,
  cross_entropy/infile.yaml,
  cross_entropy/inproject.yaml,
  cross_entropy/non_informative.yaml,
  cross_entropy/random.yaml,

  # TODO: exact match (go through all configs)

  top_k_accuracy/inproject_1.yaml,
  top_k_accuracy/inproject_3.yaml,
  top_k_accuracy/inproject_5.yaml,
  top_k_accuracy/inproject_10.yaml,

  epoch/no_args.yaml,
  lazy_statistic/learning_rate.yaml,
]
valid_metrics: [
  cross_entropy/attached.yaml,
  cross_entropy/detached.yaml,
  cross_entropy/completion.yaml,
  cross_entropy/context.yaml,
  cross_entropy/full.yaml,
  cross_entropy/commited.yaml,
  cross_entropy/common.yaml,
  cross_entropy/infile.yaml,
  cross_entropy/inproject.yaml,
  cross_entropy/non_informative.yaml,
  cross_entropy/random.yaml,

  # TODO: exact match (go through all configs)

  top_k_accuracy/inproject_1.yaml,
  top_k_accuracy/inproject_3.yaml,
  top_k_accuracy/inproject_5.yaml,
  top_k_accuracy/inproject_10.yaml,

  epoch/no_args.yaml,
]
