pre_context_prompt: ''
post_context_prompt: ''
path_comment_template: '{content}'

block_configs: [
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_ranking/negative_path_distance_ranker/no_args.yaml,
  chunk_sorting/lexicographic_sorter/no_args.yaml,
  chunk_harvesting/path_comment_harvester/empty.yaml,
]
