pre_context_prompt: ''
post_context_prompt: ''
path_comment_template: '{content}'
recalculate_random_category: True

block_configs: [
  file_filtering/null_file_filter/no_args.yaml,
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_harvesting/path_comment_harvester/empty.yaml,
]
