pre_context_prompt: "# {}\n"
post_context_prompt: "\n\n"
path_comment_template: "# {filename}\n{content}"
recalculate_random_category: True

block_configs: [
  file_filtering/empty_file_filter/no_args.yaml,
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_ranking/function_call_ranker/absolute.yaml,
  chunk_sorting/lexicographic_sorter/no_args.yaml,
  chunk_harvesting/path_comment_harvester/standard.yaml,
]
