pre_context_prompt: "# {}\n"
post_context_prompt: "\n\n"
path_comment_template: "# {filename}\n{content}"

block_configs: [
  file_chunking/file_grained_chunker/no_args.yaml,
  chunk_ranking/negative_path_distance_ranker/no_args.yaml,
  chunk_sorting/lexicographic_sorter/no_args.yaml,
  chunk_harvesting/path_comment_harvester/standard.yaml,
  context_postprocessing/line_strip_postprocessor/no_args.yaml,
  context_postprocessing/line_length_postprocessor/10_200.yaml,
]
