cache_dir:
  local: '~/.cache/huggingface/data/'
  server: '/mnt/data2/shared-data/lca/hf_cache/'

raw_datasets:
  train:
    path: 'JetBrains-Research/lca-codegen-train'
    name: null
    data_dir: 'train'
    split: 'train'

  small_context:
    path: 'JetBrains-Research/lca-project-level-code-completion'
    name: 'small_context'
    data_dir: null
    split: 'test'

  medium_context:
    path: 'JetBrains-Research/lca-project-level-code-completion'
    name: 'medium_context'
    data_dir: null
    split: 'test'

  large_context:
    path: 'JetBrains-Research/lca-project-level-code-completion'
    name: 'large_context'
    data_dir: null
    split: 'test'

  huge_context:
    path: 'JetBrains-Research/lca-project-level-code-completion'
    name: 'huge_context'
    data_dir: null
    split: 'test'

composed_datasets:  # not used now
  train:
    path: 'JetBrains-Research/context-py-train'
