run_name: ???

defaults:
  - adapter: identity_adapter/all_params
  - checkpointer: top_k_checkpointer/top_3
  - composer: chained_composer/standard
  # +additional_composer: ...
  - dataset: train_A100_server
  - logger: wandb_logger/wandb_composers
  - metrics: standard
  - model: dseek1p3
  - preprocessor: completion_loss_preprocessor/full_completion_loss_16k
  # +additional_preprocessor: ...
  - split: '256_5'
  - trainer: universal_trainer/medium_lr

  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .
